import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import MobileHeader from "@/components/header/MobileHeader";
import Footer from "@/components/footer/Footer";
import FloatingContactButtons from "@/components/FloatingContactButtons";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"], // choose the weights you need
    variable: "--font-poppins", // CSS variable for Tailwind
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={poppins.variable}>
            <body className={`antialiased`}>
                <div className="hidden md:block">
                    <Header />
                </div>
                <div className="block md:hidden">
                    <MobileHeader />
                </div>
                {children}
                <Footer />
                <FloatingContactButtons />
            </body>
        </html>
    );
}
